###
GET Http://localhost:3000/posts

###
POST Http://localhost:3000/posts
Content-Type: application/json

{
    "user": "amazing cat",
    "title": "node.js is great",
    "content": "it's true",
    "password": "1234"
}

###
GET Http://localhost:3000/posts/63d7684a3cf9684d271efa2a

###
PATCH Http://localhost:3000/posts/63d7684a3cf9684d271efa2a
Content-Type: application/json

{
    "user": "amazing candy",
    "password": "1234"
}

###
DELETE Http://localhost:3000/posts/63d8d8692f2680d759cc767a
Content-Type: application/json

{
    "password": "1234"
}


###
GET Http://localhost:3000/comments

###
POST Http://localhost:3000/comments/63d7684a3cf9684d271efa2a
Content-Type: application/json

{
    "user": "shocking person",
    "content": "node.js is the best",
    "password": "1234"
}

###
GET Http://localhost:3000/comments/63d8c3953d558fadd6510f9e

###
PATCH Http://localhost:3000/comments/63d8c3953d558fadd6510f9e
Content-Type: application/json

{
    "content": "be the best",
    "password": "1234"
}

###
DELETE Http://localhost:3000/comments/63d8c794c4d7ebe84289ba20
Content-Type: application/json

{
    "password": "1234"
}

