###
GET Http://localhost:3000/posts

###
POST Http://localhost:3000/posts
Content-Type: application/json

{
    "user": "amazing cat",
    "title": "node.js is great",
    "content": "it's true",
    "password": "1234"
}

###
GET Http://localhost:3000/posts/63d7684a3cf9684d271efa2a

###
PATCH Http://localhost:3000/posts/63d7684a3cf9684d271efa2a
Content-Type: application/json

{
    "user": "amazing god",
    "password": "1234"
}

###
DELETE Http://localhost:3000/posts/63d776e534db116ae6aa54b6
Content-Type: application/json

{
    "password": "1234"
}

###
GET Http://localhost:3000/comments

###
POST Http://localhost:3000/comments/63d7684a3cf9684d271efa2a
Content-Type: application/json

{
    "user": "shocking person",
    "content": "node.js is the best",
    "password": "1234"
}
###
GET Http://localhost:3000/comments/63d8c65d7a227a12c93758ce

###
PATCH Http://localhost:3000/comments/63d8c3953d558fadd6510f9e
Content-Type: application/json

{
    "content": "be the best"
}